// url_api
export const API_URL = "https://quangnh.xyz/v1";

// action type auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT = "LOGOUT";

// action type question
export const FETCH_QUESTIONS_PLAY_REQUEST = "FETCH_QUESTIONS_PLAY_REQUEST";
export const FETCH_QUESTIONS_PLAY_SUCCESS = "FETCH_QUESTIONS_PLAY_SUCCESS";
export const FETCH_QUESTIONS_PLAY_FAILURE = "FETCH_QUESTIONS_PLAY_FAILURE";

export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";

export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAILURE = "CREATE_QUESTION_FAILURE";

export const CREATE_ANSWER_REQUEST = "CREATE_ANSWER_REQUEST";
export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_FAILURE = "CREATE_ANSWER_FAILURE";

export const SUBMIT_QUESTIONS_REQUEST = "SUBMIT_QUESTIONS_REQUEST";
export const SUBMIT_QUESTIONS_SUCCESS = "SUBMIT_QUESTIONS_SUCCESS";
export const SUBMIT_QUESTIONS_FAILURE = "SUBMIT_QUESTIONS_FAILURE";

export const FETCH_FROFILE_REQUEST = "FETCH_FROFILE_REQUEST";
export const FETCH_FROFILE_SUCCESS = "FETCH_FROFILE_SUCCESS";
export const FETCH_FROFILE_FAILURE = "FETCH_FROFILE_FAILURE";

export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const UPLOAD_AVATAR_FAILURE = "UPLOAD_AVATAR_FAILURE";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const ADMIN = "admin";
