// url_api
export const API_URL = "https://quangnh.xyz/v1";

// action type auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT = "LOGOUT";

// action type question
export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";

export const SUBMIT_QUESTIONS_REQUEST = "SUBMIT_QUESTIONS_REQUEST";
export const SUBMIT_QUESTIONS_SUCCESS = "SUBMIT_QUESTIONS_SUCCESS";
export const SUBMIT_QUESTIONS_FAILURE = "SUBMIT_QUESTIONS_FAILURE";

export const ADMIN = "admin";
